//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogger
    {
        public int ID { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string NewValue { get; set; }
        public string EventType { get; set; }
        public string OriginalValue { get; set; }
    }
}
