//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caus()
        {
            this.Donations = new HashSet<Donation>();
        }
    
        public int ID { get; set; }
        public string CoverPhoto { get; set; }
        public string CauseContent { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Header { get; set; }
        public string ShortDescription { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> CauseDate { get; set; }
        public Nullable<int> CauseOrder { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Publish { get; set; }
        public string Currency { get; set; }
        public Nullable<double> TargetMoney { get; set; }
        public Nullable<double> StockPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
        public virtual User User { get; set; }
    }
}
