//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int ID { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<int> CauseID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string PhoneNo { get; set; }
        public string DonaterName { get; set; }
    
        public virtual Caus Caus { get; set; }
        public virtual Donation Donations1 { get; set; }
        public virtual Donation Donation1 { get; set; }
    }
}
