//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopUpUpdate
    {
        public int ID { get; set; }
        public string Header { get; set; }
        public string PopUpContent { get; set; }
        public string Link { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
